services:
  # -------------------------
  # 1. Base de Datos MySQL
  # -------------------------
  mysql_db:
    image: mysql:8.0
    container_name: poc_mysql_db
    network_mode: host  # <--- CAMBIO CLAVE
    # ports:  <--- SE ELIMINA (En modo host, usa el puerto 3306 de tu PC directamente)
    #   - "33060:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: poc_oauth2_db
    privileged: true 
    volumes:
      - db-data:/var/lib/mysql

  # -------------------------
  # 2. Servidor de Autorización
  # -------------------------
  authorization-server:
    build:
      context: ./authorization-server
      dockerfile: Dockerfile
    container_name: poc_auth_server
    network_mode: host  # <--- CAMBIO CLAVE
    # ports: <--- SE ELIMINA (Usa el 8080 de tu PC directamente)
    #   - "18080:8080" 
    environment:
      SERVER_PORT: 8080
      # CAMBIO IMPORTANTE: Como estamos en host, 'mysql_db' ahora es '127.0.0.1'
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/poc_oauth2_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "TU_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "TU_CLIENT_SECRET"
    depends_on:
      mysql_db:
        condition: service_started

  # -------------------------
  # 3. Servidor de Recursos
  # -------------------------
  resource-server:
    build:
      context: ./resource-server
      dockerfile: Dockerfile
    container_name: poc_resource_server
    network_mode: host  # <--- MODO HOST
    restart: on-failure # <--- IMPORTANTE: Para que reintente si falla al inicio
    environment:
      SERVER_PORT: 8081
      # CORRECCIÓN AQUÍ: Cambiamos 'mysql_db' por '127.0.0.1'
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/poc_oauth2_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      # CORRECCIÓN AQUÍ: Cambiamos 'authorization-server' por '127.0.0.1'
      JWT_ISSUER_URI: http://127.0.0.1:8080
    depends_on:
      mysql_db:
        condition: service_started
      authorization-server:
        condition: service_started

  # -------------------------
  # 4. Frontend Angular
  # -------------------------
  ag-prueba-front:
    build:
      context: ./ag-prueba-front
      dockerfile: Dockerfile
    container_name: poc_angular_frontend
    network_mode: host # <--- ESTO YA TE FUNCIONABA
    # ports:
    #   - "4200:80"

volumes:
  db-data:

