sonar.projectKey=eevvaahh_oauth2-springboot-angular-googlesignin-poc
sonar.organization=eevvaahh
sonar.sources=ag-prueba-front/src,authorization-server/src,resource-server/src
sonar.exclusions=**/node_modules/**,**/target/**,**/*.spec.ts
sonar.sourceEncoding=UTF-8