# -------------------------
# PUERTO DEL SERVIDOR
# -------------------------
server.port=${SERVER_PORT:9000}

# -------------------------
# DATOS DE CONEXIÓN A MYSQL
# -------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/agprueba?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -------------------------
# JPA / HIBERNATE
# -------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format-sql=true

# -------------------------
# GOOGLE OAUTH2
# -------------------------
spring.security.oauth2.client.registration.google-idp.provider=google
spring.security.oauth2.client.registration.google-idp.client-id=${GOOGLE_CLIENT_ID:TU_CLIENT_ID_LOCAL}
spring.security.oauth2.client.registration.google-idp.client-secret=${GOOGLE_CLIENT_SECRET:TU_CLIENT_SECRET_LOCAL}
spring.security.oauth2.client.registration.google-idp.scope=openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
spring.security.oauth2.client.registration.google-idp.client-name=ag-prueba-app
spring.security.oauth2.client.provider.google.user-name-attribute=email
